/**
 * 敌人/招募元数据
 * 基于 tenna-editor/src/data/enemies.ts + flags.ts + chapters.ts
 * 本文件由手动维护，不会被同步脚本覆盖
 */

// 招募标志 → 敌人索引 的映射（用于 Cafe 座位显示敌人名称）
export const RECRUITS = {
  1: 'Invalid',
  5: 'Rudinn',
  6: 'Hathy',
  11: 'Ponman',
  13: 'Rabbick',
  14: 'Bloxer',
  15: 'Jigsawry',
  20: 'JEVIL',
  22: 'Rudinn Ranger',
  23: 'Head Hathy',
  30: 'Ambyu-Lance',
  31: 'Poppup',
  32: 'Tasque',
  33: 'Werewire',
  34: 'Maus',
  35: 'Virovirokun',
  36: 'Swatchling',
  40: 'Werewerewire',
  42: 'Tasque Manager',
  44: 'Mauswheel',
  54: 'Shadowguy',
  55: 'Shuttah',
  56: 'Zapper',
  57: 'Ribbick',
  58: 'Watercooler',
  59: 'Pippins',
  60: 'Elnina',
  61: 'Lanino',
  62: 'Guei',
  63: 'Balthizard',
  64: 'Bibliox',
  65: 'Mizzle',
  66: 'Wicabel',
  67: 'Winglade',
  68: 'Organikk',
  69: 'Ms. Mizzle',
  70: 'Floradinn',
  71: 'Leafling',
  72: 'Shi',
  73: 'Shinobeetle',
  74: 'KawKaw',
  75: 'Sheary',
  76: 'Netskie',
  77: 'Terakota',
};

/**
 * 敌人元数据
 * 键为敌人索引（对应 GameMaker 的 enemy ID）
 * recruitable: 是否可招募
 * recruitFlag: 招募标志在 flags 数组中的索引
 * recruitCount: 招募数量（多人敌人如 Ambyu-Lance 有 4 个）
 * chapter: 该敌人首次出现的章节
 */
export const ENEMIES_META = {
  // Ch1
  1:  { displayName: 'Debug Enemy', recruitable: false, recruitFlag: 601, chapter: 1 },
  2:  { displayName: 'Lancer 1', recruitable: false, recruitFlag: 602, chapter: 1 },
  3:  { displayName: 'Dummy', recruitable: false, recruitFlag: 603, chapter: 1 },
  4:  { displayName: 'Ralsei (tutorial)', recruitable: false, recruitFlag: 604, chapter: 1 },
  5:  { displayName: 'Rudinn', recruitable: true, recruitFlag: 605, recruitCount: 1, chapter: 1 },
  6:  { displayName: 'Hathy', recruitable: true, recruitFlag: 606, recruitCount: 1, chapter: 1 },
  7:  { displayName: 'Clover 1', recruitable: false, recruitFlag: 607, chapter: 1 },
  9:  { displayName: 'C. Round', recruitable: false, recruitFlag: 609, chapter: 1 },
  10: { displayName: 'K. Round 1', recruitable: false, recruitFlag: 610, chapter: 1 },
  11: { displayName: 'Ponman', recruitable: true, recruitFlag: 611, recruitCount: 1, chapter: 1 },
  12: { displayName: 'Lancer 2', recruitable: false, recruitFlag: 612, chapter: 1 },
  13: { displayName: 'Rabbick', recruitable: true, recruitFlag: 613, recruitCount: 1, chapter: 1 },
  14: { displayName: 'Bloxer', recruitable: true, recruitFlag: 614, recruitCount: 1, chapter: 1 },
  15: { displayName: 'Jigsawry', recruitable: true, recruitFlag: 615, recruitCount: 1, chapter: 1 },
  16: { displayName: 'Clover 2', recruitable: false, recruitFlag: 616, chapter: 1 },
  17: { displayName: 'DoomTank', recruitable: false, recruitFlag: 617, chapter: 1 },
  18: { displayName: 'Lancer 3', recruitable: false, recruitFlag: 618, chapter: 1 },
  19: { displayName: 'Susie&Lancer', recruitable: false, recruitFlag: 619, chapter: 1 },
  20: { displayName: 'JEVIL', recruitable: false, recruitFlag: 620, chapter: 1 },
  21: { displayName: 'K. Round 2', recruitable: false, recruitFlag: 621, chapter: 1 },
  22: { displayName: 'Rudinn Ranger', recruitable: true, recruitFlag: 622, recruitCount: 1, chapter: 1 },
  23: { displayName: 'Head Hathy', recruitable: true, recruitFlag: 623, recruitCount: 1, chapter: 1 },
  25: { displayName: 'King', recruitable: false, recruitFlag: 625, chapter: 1 },
  // Ch2
  30: { displayName: 'Ambyu-Lance', recruitable: true, recruitFlag: 630, recruitCount: 4, chapter: 2 },
  31: { displayName: 'Poppup', recruitable: true, recruitFlag: 631, recruitCount: 3, chapter: 2 },
  32: { displayName: 'Tasque', recruitable: true, recruitFlag: 632, recruitCount: 5, chapter: 2 },
  33: { displayName: 'Werewire', recruitable: true, recruitFlag: 633, recruitCount: 6, chapter: 2 },
  34: { displayName: 'Maus', recruitable: true, recruitFlag: 634, recruitCount: 3, chapter: 2 },
  35: { displayName: 'Virovirokun', recruitable: true, recruitFlag: 635, recruitCount: 4, chapter: 2 },
  36: { displayName: 'Swatchling', recruitable: true, recruitFlag: 636, recruitCount: 5, chapter: 2 },
  37: { displayName: "Cap'n", recruitable: false, recruitFlag: 637, chapter: 2 },
  38: { displayName: 'K_K', recruitable: false, recruitFlag: 638, chapter: 2 },
  39: { displayName: 'Sweet', recruitable: false, recruitFlag: 639, chapter: 2 },
  40: { displayName: 'Werewerewire', recruitable: true, recruitFlag: 640, recruitCount: 1, chapter: 2 },
  41: { displayName: 'GrazeTest', recruitable: false, recruitFlag: 641, chapter: 2 },
  42: { displayName: 'Tasque Manager', recruitable: true, recruitFlag: 642, recruitCount: 1, chapter: 2 },
  43: { displayName: 'Berdly 1', recruitable: false, recruitFlag: 643, chapter: 2 },
  44: { displayName: 'Mauswheel', recruitable: true, recruitFlag: 644, recruitCount: 1, chapter: 2 },
  45: { displayName: 'Rouxls 1', recruitable: false, recruitFlag: 645, chapter: 2 },
  46: { displayName: 'Berdly 2', recruitable: false, recruitFlag: 646, chapter: 2 },
  47: { displayName: 'Clover (dojo)', recruitable: false, recruitFlag: 647, chapter: 2 },
  48: { displayName: 'Queen', recruitable: false, recruitFlag: 648, chapter: 2 },
  49: { displayName: 'Spamton', recruitable: false, recruitFlag: 649, chapter: 2 },
  50: { displayName: 'Spamton NEO', recruitable: false, recruitFlag: 650, chapter: 2 },
  51: { displayName: 'GIGA Queen', recruitable: false, recruitFlag: 651, chapter: 2 },
  52: { displayName: 'Jigsaw Joe (dojo)', recruitable: false, recruitFlag: 652, chapter: 2 },
  53: { displayName: 'Pipis', recruitable: false, recruitFlag: 653, chapter: 2 },
  // Ch3
  54: { displayName: 'Shadowguy', recruitable: true, recruitFlag: 654, recruitCount: 25, chapter: 3 },
  55: { displayName: 'Shuttah', recruitable: true, recruitFlag: 655, recruitCount: 2, chapter: 3 },
  56: { displayName: 'Zapper', recruitable: true, recruitFlag: 656, recruitCount: 2, chapter: 3 },
  57: { displayName: 'Ribbick', recruitable: true, recruitFlag: 657, recruitCount: 3, chapter: 3 },
  58: { displayName: 'Watercooler', recruitable: true, recruitFlag: 658, recruitCount: 1, chapter: 3 },
  59: { displayName: 'Pippins', recruitable: true, recruitFlag: 659, recruitCount: 5, chapter: 3 },
  60: { displayName: 'Elnina', recruitable: true, recruitFlag: 660, recruitCount: 1, chapter: 3 },
  61: { displayName: 'Lanino', recruitable: true, recruitFlag: 661, recruitCount: 1, chapter: 3 },
  101: { displayName: 'Boss 1', recruitable: false, chapter: 3 },
  102: { displayName: 'Rouxls 2', recruitable: false, chapter: 3 },
  103: { displayName: 'Tenna 1', recruitable: false, chapter: 3 },
  104: { displayName: 'Knight', recruitable: false, chapter: 3 },
  105: { displayName: 'Tenna 2', recruitable: false, chapter: 3 },
  106: { displayName: 'Elnina (dojo)', recruitable: false, chapter: 3 },
  107: { displayName: 'Lanino (dojo)', recruitable: false, chapter: 3 },
  // Ch4
  62: { displayName: 'Guei', recruitable: true, recruitFlag: 662, recruitCount: 3, chapter: 4 },
  63: { displayName: 'Balthizard', recruitable: true, recruitFlag: 663, recruitCount: 5, chapter: 4 },
  64: { displayName: 'Bibliox', recruitable: true, recruitFlag: 664, recruitCount: 3, chapter: 4 },
  65: { displayName: 'Mizzle', recruitable: true, recruitFlag: 665, recruitCount: 2, chapter: 4 },
  66: { displayName: 'Wicabel', recruitable: true, recruitFlag: 666, recruitCount: 2, chapter: 4 },
  67: { displayName: 'Winglade', recruitable: true, recruitFlag: 667, recruitCount: 2, chapter: 4 },
  68: { displayName: 'Organikk', recruitable: true, recruitFlag: 668, recruitCount: 3, chapter: 4 },
  69: { displayName: 'Miss Mizzle', recruitable: true, recruitFlag: 669, recruitCount: 1, chapter: 4 },
  108: { displayName: 'Titan', recruitable: false, chapter: 4 },
  109: { displayName: 'Titan Spawn', recruitable: false, chapter: 4 },
  // Ch5
  70: { displayName: 'Floradinn', recruitable: true, recruitFlag: 670, recruitCount: 2, chapter: 5 },
  71: { displayName: 'Leafling', recruitable: true, recruitFlag: 671, recruitCount: 2, chapter: 5 },
  72: { displayName: 'Shi', recruitable: true, recruitFlag: 672, recruitCount: 4, chapter: 5 },
  73: { displayName: 'Shinobeetle', recruitable: true, recruitFlag: 673, recruitCount: 3, chapter: 5 },
  74: { displayName: 'KawKaw', recruitable: true, recruitFlag: 674, recruitCount: 2, chapter: 5 },
  75: { displayName: 'Sheary', recruitable: true, recruitFlag: 675, recruitCount: 2, chapter: 5 },
  76: { displayName: 'Netskie', recruitable: true, recruitFlag: 676, recruitCount: 2, chapter: 5 },
  77: { displayName: 'Terakota', recruitable: true, recruitFlag: 677, recruitCount: 2, chapter: 5 },
};

/** Cafe 座位标志索引 */
export const CAFE_SEATS = [
  { id: 'cafe-top-left', flag: 800, label: 'Top Left' },
  { id: 'cafe-top-right', flag: 801, label: 'Top Right' },
  { id: 'cafe-bottom-left', flag: 802, label: 'Bottom Left' },
  { id: 'cafe-bottom-right', flag: 803, label: 'Bottom Right' },
];
